import {access,mkdtemp,realpath,writeFile,readFile,rm,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {createHash} from 'node:crypto';
import {compare,resolve,pendingCount} from './review.mjs';
import {wordPython as python,pandoc,dataDir,sandbox,pythonRuntime,dependencyRoots,sandboxProfile} from './runtime.mjs';
const run=promisify(execFile), root=fileURLToPath(new URL('../',import.meta.url));
const engine=fileURLToPath(new URL('./word_engine.py',import.meta.url));
export const MAX_WORD_BYTES=4_000_000;
const digest=bytes=>createHash('sha256').update(bytes).digest('hex');
let busy=false;
export async function wordAvailable(){try{if(!python||!pandoc||!sandbox)return false;await access(engine);return !!(await pythonRuntime(python)).modules.lxml;}catch{return false;}}
function decoded(value){if(typeof value!=='string'||value.length>Math.ceil(MAX_WORD_BYTES/3)*4||!value.length||value.length%4!==0||/[^A-Za-z0-9+/=]/.test(value)||value.indexOf('=')>=0&&!/^={1,2}$/.test(value.slice(value.indexOf('='))))throw Error('Choose a Word .docx file under 4 MB.');const bytes=Buffer.from(value,'base64');if(bytes.toString('base64')!==value)throw Error('The Word file encoding is invalid.');if(bytes.length>MAX_WORD_BYTES||bytes.length<4||bytes.subarray(0,2).toString()!=='PK')throw Error('This is not a supported Word .docx file.');return bytes;}
function filename(value){return path.basename(String(value||'Document.docx')).replace(/[\u0000-\u001f]/g,'')||'Document.docx';}
function checkedHash(value){if(typeof value!=='string'||!/^[a-f0-9]{64}$/.test(value))throw Error('The original Word file reference is invalid.');return value;}
async function saveOriginal(bytes,name,expected){const hash=digest(bytes);if(expected&&hash!==expected)throw Error('The original Word file does not match its recorded hash.');const directory=path.join(dataDir,'originals');await mkdir(directory,{recursive:true,mode:0o700});try{await writeFile(path.join(directory,hash+'.docx'),bytes,{flag:'wx',mode:0o600});}catch(e){if(e.code!=='EEXIST')throw e;const stored=await readFile(path.join(directory,hash+'.docx'));if(digest(stored)!==hash)throw Error('The preserved Word file failed its integrity check.');}return {hash,name:filename(name),size:bytes.length,format:'docx'};}
export async function originalWord(hash){checkedHash(hash);let bytes;try{bytes=await readFile(path.join(dataDir,'originals',hash+'.docx'));}catch{throw Error('The original Word file is unavailable on this Mac. Open a portable review containing the original, or import the Word file again.');}if(digest(bytes)!==hash)throw Error('The preserved Word file failed its integrity check.');return {data:bytes.toString('base64'),hash,size:bytes.length};}
export async function restoreWordFiles(files){if(!Array.isArray(files)||files.length>2)throw Error('A review can contain up to two original Word files.');const result=[];for(const file of files){checkedHash(file.hash);const stored=file.data?await saveOriginal(decoded(file.data),file.name,file.hash):await originalWord(file.hash);if(file.size!==undefined&&file.size!==stored.size)throw Error('The original Word file size does not match this review.');result.push({hash:stored.hash,size:stored.size,name:filename(file.name),format:'docx',role:file.role||'source'});}return result;}
async function withEngine(mode,payload,input){
 if(!await wordAvailable())throw Error('Word conversion is unavailable on this Mac. The README lists the local conversion dependencies.');
 if(busy)throw Error('A Word document is being converted. Please try again shortly.');busy=true;
 let job;
 try{job=await realpath(await mkdtemp(path.join(tmpdir(),'margin-word-')));const executable=python, converter=await realpath(pandoc);
  const profile=sandboxProfile(job,[...(await pythonRuntime(python)).roots,...dependencyRoots(python),...dependencyRoots(pandoc),path.dirname(engine)]);
  const request={...payload,inputPath:path.join(job,'input.docx'),outputPath:path.join(job,'output.docx')};if(input)await writeFile(request.inputPath,input);
  await writeFile(path.join(job,'request.json'),JSON.stringify(request));
  const env={PATH:'/usr/bin:/bin',HOME:job,TMPDIR:job,LANG:'en_US.UTF-8',FOLIO_PANDOC:converter,PYTHONNOUSERSITE:'1',PYTHONDONTWRITEBYTECODE:'1'};
  let output;try{output=await run(sandbox,['-p',profile,executable,'-I','-B',engine,mode,path.join(job,'request.json')],{cwd:job,env,timeout:45000,maxBuffer:5_000_000});}catch(e){let info;try{info=JSON.parse(String(e.stdout));}catch{}throw Error(info?.error||String(e.stderr||e.stdout||e.message).slice(0,1500)||'Word conversion could not be completed.');}
  const result=JSON.parse(output.stdout);if(result.error)throw Error(result.error);if(mode==='export'){if(!result.written)throw Error('Word export could not safely place '+(result.unplacedComments?.length||'one or more')+' comment(s). The review and original are preserved. Save a Margin review to keep all comments.');result.data=(await readFile(request.outputPath)).toString('base64');}return result;
 }finally{busy=false;if(job)await rm(job,{recursive:true,force:true});}
}
function rangedSegments(review){let before=0,after=0;return review.segments.map(s=>{const row={...s,beforeStart:before,beforeEnd:before+s.before.length,afterStart:after,afterEnd:after+s.after.length};before=row.beforeEnd;after=row.afterEnd;return row;});}
export function anchorComments(review,items){const segments=rangedSegments(review),comments={},unmatched=[];
 for(const item of items||[]){let matches=[];for(const side of ['after','before']){const anchor=item[side+'Anchor'];if(anchor&&Number.isInteger(anchor.start)&&Number.isInteger(anchor.end)&&review.segments.map(s=>s[side]).join('').slice(anchor.start,anchor.end)===anchor.source)matches=segments.filter(s=>!s.preamble&&!s.end&&s[side+'Start']<=anchor.start&&s[side+'End']>anchor.start);if(matches.length)break;}
  if(!matches.length){for(const side of ['after','before']){const fragment=item[side+'Anchor']?.source;if(fragment)matches=segments.filter(s=>!s.preamble&&!s.end&&s[side].includes(fragment));if(matches.length===1)break;}}
  if(matches.length!==1){unmatched.push(item);continue;}
  const id=matches[0].id;(comments[id]??=[]).push({text:String(item.text||''),at:String(item.at||item.date||''),author:String(item.author||''),origin:'word',wordId:String(item.id??''),sourceAnchor:item.afterAnchor?.source||item.beforeAnchor?.source||'',anchorTextBefore:item.anchorTextBefore||'',anchorTextAfter:item.anchorTextAfter||''});
 }return {comments,unmatched};
}
export async function importWord({data,name,title}){const bytes=decoded(data),result=await withEngine('import',{title:String(title||filename(name).replace(/\.docx$/i,''))},bytes);const review=compare(result.before,result.after),mapped=anchorComments(review,result.comments);const warnings=[...(result.warnings||[])];if(mapped.unmatched.length)warnings.push(`${mapped.unmatched.length} Word comment(s) could not be attached to a passage. They are retained in the conversion record and original Word file.`);const attachment=await saveOriginal(bytes,name);
 return {...result,comments:mapped.comments,unmatchedComments:mapped.unmatched,warnings,attachment,beforeHash:review.beforeHash,afterHash:review.afterHash};}
export async function exportWord(session,mode){if(!['clean','tracked'].includes(mode))throw Error('Unknown Word export mode.');const review=compare(session.before,session.after);const after=resolve(review,session.decisions||{});if(pendingCount(review,session.decisions||{}))throw Error('Review every change before exporting a reviewed Word document.');if(session.conversion?.reports?.some(r=>r.unmatchedComments?.length))throw Error('This review has Word comments without a safe passage anchor. They remain in the original and Margin review file. Resolve their context before exporting to Word.');const ids=new Set(review.segments.map(s=>s.id));for(const [id,notes] of Object.entries(session.comments||{}))if(!ids.has(id)||!Array.isArray(notes))throw Error('A comment does not match this review.');const comments=[];for(const s of review.segments){for(const note of session.comments?.[s.id]||[]){const current=s.type==='equal'?s.after:session.decisions[s.id]==='rejected'?s.before:s.after;comments.push({sourceAnchor:current||s.before,author:note.origin==='word'?note.author||'Unspecified author':'Local reviewer',at:note.at,text:note.text,anchorText:session.decisions[s.id]==='rejected'?note.anchorTextBefore:note.anchorTextAfter});}}
 const result=await withEngine('export',{before:session.before,after,mode,comments,author:'Margin'});return {...result,sourceHash:digest(after),mode};}
const escapeTex=s=>s.replace(/[\\%&#_${}^~]/g,c=>({'\\':'\\textbackslash{}','%':'\\%','&':'\\&','#':'\\#','$':'\\$','_':'\\_','{':'\\{','}':'\\}','^':'\\textasciicircum{}','~':'\\textasciitilde{}'}[c]));
export function importText(text,title='Document'){if(typeof text!=='string'||Buffer.byteLength(text,'utf8')>150000)throw Error('Paste text under 150 KB.');const body=text.replace(/\r\n?/g,'\n').split(/\n\s*\n/).map(s=>escapeTex(s.trim())).filter(Boolean).join('\n\n');if(!body)throw Error('Paste some document text.');const source='\\documentclass[11pt,a4paper]{article}\n\\usepackage[margin=28mm]{geometry}\n\\usepackage{fontspec}\n\\setmainfont{texgyrepagella}[Extension=.otf,UprightFont=*-regular,BoldFont=*-bold,ItalicFont=*-italic,BoldItalicFont=*-bolditalic]\n\\usepackage{parskip}\n\\begin{document}\n\n'+body+'\n\n\\end{document}\n';return {before:source,after:source,title};}
export function mapComparisonComments(before,after,sources){const target=rangedSegments(compare(before,after)),comments={};for(const input of sources||[]){if(!['before','after'].includes(input.side)||input.source!==(input.side==='before'?before:after))throw Error('The comment source does not match this comparison.');const own=rangedSegments(compare(input.source,input.source));for(const [id,notes] of Object.entries(input.comments||{})){const paragraph=own.find(s=>s.id===id);if(!paragraph||!Array.isArray(notes))throw Error('An imported comment could not be matched to its original passage.');const offset=paragraph.afterStart;const matches=target.filter(s=>!s.preamble&&!s.end&&s[input.side+'Start']<=offset&&s[input.side+'End']>offset);if(matches.length!==1)throw Error('A Word comment could not be placed safely in the comparison. Open that document on its own to inspect the comment.');const output=comments[matches[0].id]??=[];for(const note of notes){if(!output.some(n=>n.wordId===note.wordId&&n.text===note.text&&n.author===note.author&&n.at===note.at))output.push({...note});}}}return {comments};}
